version: "3.8"

services:
  mock-api-server:
    image: php:8.2-apache
    ports:
      - "5555:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      sh -c "
        a2enmod rewrite &&
        echo 'ServerName localhost' >> /etc/apache2/apache2.conf &&
        echo '<Directory /var/www/html>' >> /etc/apache2/sites-available/000-default.conf &&
        echo '    AllowOverride All' >> /etc/apache2/sites-available/000-default.conf &&
        echo '    Require all granted' >> /etc/apache2/sites-available/000-default.conf &&
        echo '    DirectoryIndex server.php index.php index.html' >> /etc/apache2/sites-available/000-default.conf &&
        echo '</Directory>' >> /etc/apache2/sites-available/000-default.conf &&
        apache2-foreground
      "
